# Generated by Django 5.0 on 2023-12-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_contact_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='link',
            field=models.CharField(max_length=225),
        ),
    ]
