# Generated by Django 5.0 on 2023-12-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_contacts_delete_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='contacts',
            new_name='contact',
        ),
    ]
